name: Checks

on:
  push:
  pull_request:

jobs:
  flake-check:
    name: ${{ matrix.system }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
          - system: aarch64-darwin
            runner: macos-15

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Check flake
        run: nix flake check --no-update-lock-file
